import numpy as np

def map_data(df):
    df['MSZoning'] = df['MSZoning'].map({'A': 1,'C (all)':2, 'FV':3, 'I':4, 'RH':5, 'RL':6, 'RP':7, 'RM':8 })
    df['Street'] = df['Street'].map({'Grvl':1 ,'Pave': 2})
    df['Alley'] = df['Alley'].map({'NA': 1, 'Grvl':2 ,'Pave': 3})
    df['LotShape'] = df['LotShape'].map({'Reg':1, 'IR1':2 ,'IR2':3, 'IR3':4})
    df['LandContour'] = df['LandContour'].map({'Lvl': 4,'Bnk': 3, 'HLS': 2, 'Low': 1})
    df['Utilities'] = df['Utilities'].map({ 'AllPub':4, 'NoSewr':3, 'NoSeWa' :1, 'ELO': 1})
    df['LotConfig'] = df['LotConfig'].map({'Inside': 1, 'Corner': 2, 'CulDSac': 3, 'FR2': 4, 'FR3':5})
    df['LandSlope'] = df['LandSlope'].map({'Gtl': 3, 'Mod': 2, 'Sev': 1})
    df['Neighborhood'] = df['Neighborhood'].map({ 'Blmngtn': 1, 'Blueste': 2, 'BrDale': 3, 'BrkSide': 4, 'ClearCr': 5, 'CollgCr': 6, 'Crawfor': 7, 'Edwards': 8,'Gilbert': 9, 'IDOTRR': 10, 'MeadowV': 11, 'Mitchel': 12, 'Names': 13, 'NoRidge': 14, 'NPkVill': 15,'NridgHt': 16, 'NWAmes': 17, 'OldTown': 18, 'SWISU': 19, 'Sawyer': 20, 'SawyerW': 21, 'Somerst': 22, 'StoneBr': 23, 'Timber': 24, 'Veenker':25})
    df['Condition1'] = df['Condition1'].map({ 'Artery': 1, 'Feedr': 2, 'Norm': 3, 'RRNn': 4, 'RRAn': 5, 'PosN': 6, 'PosA': 7, 'RRNe': 8, 'RRAe':9})
    df['Condition2'] = df['Condition2'].map({ 'Artery': 1, 'Feedr': 2, 'Norm': 3, 'RRNn': 4, 'RRAn': 5, 'PosN': 6, 'PosA': 7, 'RRNe': 8, 'RRAe':9})
    df['BldgType'] = df['BldgType'].map({'1Fam': 1, '2FmCon': 2, 'Duplx': 3, 'TwnhsE': 4, 'TwnhsI': 5})
    df['HouseStyle'] = df['HouseStyle'].map({ '1Story': 1, '1.5Fin': 2, '1.5Unf': 3, '2Story': 4, '2.5Fin': 5, '2.5Unf': 6, 'SFoyer': 7, 'SLvl': 8})
    df['RoofStyle'] = df['RoofStyle'].map({'Flat': 1, 'Gable': 2, 'Gambrel': 3, 'Hip': 4, 'Mansard': 5, 'Shed': 6})
    df['RoofMatl'] = df['RoofMatl'].map({'ClyTile': 1, 'CompShg': 2, 'Membran': 3, 'Metal': 4, 'Roll': 5, 'Tar&Grv': 6, 'WdShake': 7, 'WdShngl':8})
    df['Exterior1st'] = df['Exterior1st'].map({'AsbShng': 1, 'AsphShn': 2, 'BrkComm': 3, 'BrkFace': 4, 'CBlock': 5, 'CemntBd': 6, 'HdBoard': 7, 'ImStucc':8, 'MetalSd': 9 , 'Other': 10, 'Plywood': 11, 'PreCast':12, 'Stone': 13,'Stucco': 14, 'VinylSd': 15, 'Wd Sdng': 16, 'WdShing': 17})
    df['Exterior2nd'] = df['Exterior2nd'].map({'AsbShng': 1, 'AsphShn': 2, 'BrkComm': 3, 'BrkFace': 4, 'CBlock': 5, 'CemntBd': 6, 'HdBoard': 7, 'ImStucc':8, 'MetalSd': 9 , 'Other': 10, 'Plywood': 11, 'PreCast':12, 'Stone': 13,'Stucco': 14, 'VinylSd': 15, 'Wd Sdng': 16, 'WdShing': 17})
    df['MasVnrType'] = df['MasVnrType'].map({'BrkCmn': 1, 'BrkCmn': 2, 'CBlock': 3, 'None': 4, 'Stone': 5})
    df['ExterQual'] = df['ExterQual'].map({'Ex': 5, 'Gd': 4, 'TA': 3, 'Fa': 2, 'Po': 1})
    df['ExterCond'] = df['ExterCond'].map({'Ex': 5, 'Gd': 4, 'TA': 3, 'Fa': 2, 'Po': 1})
    df['Foundation'] = df['Foundation'].map({'BrkTil': 1, 'CBlock': 2, 'PConc': 3, 'Slab': 4, 'Stone': 5, 'Wood': 6})
    df['BsmtQual'] = df['BsmtQual'].map({'Ex': 5, 'Gd': 4, 'TA': 3, 'Fa': 2, 'Po': 1, 'NA': 0})
    df['BsmtCond'] = df['BsmtCond'].map({'Ex': 5, 'Gd': 4, 'TA': 3, 'Fa': 2, 'Po': 1, 'NA': 0})
    df['BsmtExposure'] = df['BsmtExposure'].map({'Gd': 4, 'Av': 3, 'Mn': 2, 'No': 1, 'NA': 0})
    df['BsmtFinType1'] = df['BsmtFinType1'].map({'NA': 0,'Unf': 1, 'LwQ': 2, 'Rec': 3, 'BLQ': 4, 'ALQ': 5, 'GLQ': 6})
    df['BsmtFinType2'] = df['BsmtFinType2'].map({'NA': 0,'Unf': 1, 'LwQ': 2, 'Rec': 3, 'BLQ': 4, 'ALQ': 5, 'GLQ': 6})
    df['Heating'] = df['Heating'].map({'Floor': 1, 'GasA': 2, 'GasW': 3, 'Grav': 4, 'OthW': 5, 'Wall': 6})
    df['HeatingQC'] = df['HeatingQC'].map({'Po': 1, 'Fa': 2, 'TA': 3, 'Gd': 4, 'Ex': 5})
    df['CentralAir'] = df['CentralAir'].map({'N': 0, 'Y': 1})
    df['Electrical'] = df['Electrical'].map({'SBrkr': 1, 'FuseA': 2, 'FuseF': 3, 'FuseP': 4, 'Mix': 5})
    df['KitchenQual'] = df['KitchenQual'].map({'Po': 1, 'Fa': 2, 'TA': 3, 'Gd': 4, 'Ex': 5})
    df['Functional'] = df['Functional'].map({'Sal': 1, 'Sev': 2, 'Maj2': 3, 'Maj1': 4, 'Mod': 5, 'Min2': 6, 'Min1': 7, 'Typ':8})
    df['FireplaceQu'] = df['FireplaceQu'].map({'TA': 1, 'Gd': 2, 'Ex': 3})
    df['GarageType'] = df['GarageType'].map({'NA': 0, 'Detchd': 1, 'CarPort': 2, 'BuiltIn': 3, 'Basment': 4, 'Attchd': 5, '2Types': 6})
    df['GarageFinish'] = df['GarageFinish'].map({'NA': 0,'Unf': 1, 'RFn': 2, 'Fin': 3})
    df['GarageQual'] = df['GarageQual'].map({'NA':0, 'Po': 1, 'Fa': 2, 'TA': 3, 'Gd': 4, 'Ex': 5})
    df['GarageCond'] = df['GarageCond'].map({'NA':0, 'Po': 1, 'Fa': 2, 'TA': 3, 'Gd': 4, 'Ex': 5})
    df['PavedDrive'] = df['PavedDrive'].map({'N': 1, 'P': 2, 'Y': 3})
    df['PoolQC'] = df['PoolQC'].map({'NA':0, 'Fa': 1, 'TA': 2, 'Gd': 3, 'Ex': 4})
    df['Fence'] = df['Fence'].map({'NA':0,'MnWw': 1, 'GdWo': 2, 'MnPrv': 3, 'GdPrv': 4})
    df['MiscFeature'] = df['MiscFeature'].map({'NA':0,'TenC': 1, 'Shed': 2, 'Othr': 3, 'Gar2': 4, 'Elev': 5})
    df['SaleType'] = df['SaleType'].map({'WD': 1, 'CWD': 2, 'VWD': 3, 'New': 4, 'COD': 5, 'Con': 6, 'ConLw': 7, 'ConLI':8, 'ConLD': 9, 'Oth': 10 })
    df['SaleCondition'] = df['SaleCondition'].map({'Normal': 1, 'Abnorml': 2, 'AdjLand': 3, 'Alloca': 4, 'Family': 5, 'Partial': 6})

    return df
    # return np.nan_to_num(df)
